# === requis par le chart ===
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []

autoscaling:
  enabled: false

# === ton app cast ===
image:
  repository: abeonim/casts-api
  tag: v8.0

containerPort: 8000

service:
  type: NodePort
  port: 80
  targetPort: 8000
  nodePort: 30008

env:
  DATABASE_URI: "postgresql://cast:castpass@cast-db:5432/castdb"
  DATABASE_URL: "postgresql://cast:castpass@cast-db:5432/castdb"

probes:
  enabled: false
